stages:
    - test
    - deploy

test:
    stage: test
    script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip sqlite3
    - pip3 install -r requirements.txt
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test

staging:
    stage: deploy
    script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - export HEROKU_STAGING_API_KEY="HelloWorld123"
    - echo $HEROKU_STAGING_API_KEY
    - dpl --provider=heroku --app=padel-analytics --api-key=$HEROKU_STAGING_API_KEY
    only:
    - 290-heroku-stage
