  version: '3'

  services:
    web:
      build: .
      # command: python3 manage.py runserver 0.0.0.0:8000
      command: gunicorn padelanalytics.settings.prod.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
