"""
Django settings for padelanalytics project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

from .common import *  # noqa: F403, F401

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_PADELANAL_SECRET_KEY')
PADEL_GOOGLE_TRACK_ID = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
TEMPLATE_DEBUG = False

ALLOWED_HOSTS = ['62.75.188.101', 'www.padelanalytics.de', 'padelanalytics.de']

WSGI_APPLICATION = 'padelanalytics.settings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
