BEGIN TRANSACTION;
DELETE FROM tournaments_padelranking;
DELETE FROM tournaments_player;
DELETE FROM tournaments_person;
DELETE FROM tournaments_multigame;
DELETE FROM tournaments_game;
DELETE FROM tournaments_tournament_teams;
DELETE FROM tournaments_team;
DELETE FROM tournaments_tournament;
DELETE FROM sqlite_sequence WHERE name='tournaments_padelranking';
DELETE FROM sqlite_sequence WHERE name='tournaments_player';
DELETE FROM sqlite_sequence WHERE name='tournaments_person';
DELETE FROM sqlite_sequence WHERE name='tournaments_multigame';
DELETE FROM sqlite_sequence WHERE name='tournaments_game';
DELETE FROM sqlite_sequence WHERE name='tournaments_tournament_teams';
DELETE FROM sqlite_sequence WHERE name='tournaments_team';
DELETE FROM sqlite_sequence WHERE name='tournaments_tournament';
COMMIT;
