BEGIN TRANSACTION;
UPDATE tournaments_tournament SET club_id=29, date="2015-10-04", country="Germany", city="Herne" WHERE name="Deutsche Meisterschaft 2015 - Herren" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=20, date="2016-01-31", country="Germany", city="Essen" WHERE name="Essener Open 2016" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=29, date="2016-03-06", country="Germany", city="Herne" WHERE name="Herner Open 2016" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=9, date="2016-05-08", country="Germany", city="Berlin" WHERE name="FIP 100 II Berlin Padel Open" AND padel_serie="GPS-2000";
UPDATE tournaments_tournament SET club_id=9, date="2016-05-08", country="Germany", city="Berlin" WHERE name="Berliner Open 2016 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=15, date="2016-05-22", country="Germany", city="Frankfurt am Main" WHERE name="Frankfurter Open 2016" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=12, date="2016-06-05", country="Germany", city="München" WHERE name="III Münchener Frühlingsturnier 2016 - Herren" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=12, date="2016-06-05", country="Germany", city="München" WHERE name="III Münchener Frühlingsturnier 2016 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=12, date="2016-07-10", country="Germany", city="München" WHERE name="III Münchener Sommerturnier 2016 - Herren" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=2, date="2016-07-16", country="Germany", city="Hamburg" WHERE name="Hamburger Open 2016" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=14, date="2016-07-31", country="Germany", city="Berlin" WHERE name="IV. Berlin Classics 2016" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=10, date="2016-08-21", country="Germany", city="Baden-Baden" WHERE name="Badener Open 2016" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=18, date="2016-08-28", country="Germany", city="Espelkamp" WHERE name="Espelkamper Open 2016 - Kat. A" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=18, date="2016-08-28", country="Germany", city="Espelkamp" WHERE name="Espelkamper Open 2016 - Kat. B" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=19, date="2016-09-11", country="Germany", city="Köln" WHERE name="Kölner Open 2016" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=9, date="2016-09-18", country="Germany", city="Berlin" WHERE name="Berliner Open 2016 - Herren Kat. A" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=9, date="2016-09-18", country="Germany", city="Berlin" WHERE name="Berliner Open 2016 - Herren Kat. B" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=9, date="2016-09-18", country="Germany", city="Berlin" WHERE name="Berliner Open 2016 - Mixed";
UPDATE tournaments_tournament SET club_id=8, date="2016-09-18", country="Germany", city="Worms" WHERE name="Wormser Open 2016" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=17, date="2016-09-25", country="Germany", city="Weyhe" WHERE name="Weyher Open 2016" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=29, date="2016-10-02", country="Germany", city="Herne" WHERE name="FIP 100 II Herne NRW Padel Open - Herren" AND padel_serie="GPS-2000";
UPDATE tournaments_tournament SET club_id=29, date="2016-10-02", country="Germany", city="Herne" WHERE name="FIP 100 II Herne NRW Padel Open - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=3, date="2016-10-16", country="Germany", city="Köln" WHERE name="Deutsche Meisterschaft 2016 - Herren" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=3, date="2017-01-29", country="Germany", city="Köln" WHERE name="Kick-Off German Padel Series 2017" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=3, date="2017-01-29", country="Germany", city="Köln" WHERE name="Kick-Off German Padel Series 2017 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=9, date="2017-05-07", country="Germany", city="Berlin" WHERE name="FIP 100 III Berlin Padel Open" AND padel_serie="GPS-1200";
UPDATE tournaments_tournament SET club_id=17, date="2017-06-10", country="Germany", city="Weyhe" WHERE name="I Weyher Lokales Turnier 2017 Kat. A" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=17, date="2017-06-10", country="Germany", city="Weyhe" WHERE name="I Weyher Lokales Turnier 2017 Kat. B" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=2, date="2017-06-18", country="Germany", city="Hamburg" WHERE name="Hamburger Open 2017" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=12, date="2017-06-25", country="Germany", city="München" WHERE name="IV Münchener Frühlingsturnier 2017 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=12, date="2017-06-25", country="Germany", city="München" WHERE name="IV Münchener Frühlingsturnier 2017 - Herren" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=20, date="2017-07-01", country="Germany", city="Essen" WHERE name="Essener Open 2017" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=9, date="2017-07-09", country="Germany", city="Berlin" WHERE name="Berliner Lokales Turnier 2017 - Herren" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=9, date="2017-07-09", country="Germany", city="Berlin" WHERE name="Berliner Lokales Turnier 2017 - Mixed" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=16, date="2017-07-16", country="Germany", city="Cuxhaven" WHERE name="Cuxhavener Open 2017" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=10, date="2017-07-23", country="Germany", city="Baden-Baden" WHERE name="Badener Open 2017" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=12, date="2017-07-23", country="Germany", city="München" WHERE name="IV Münchener Sommerturnier 2017 - Herren" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=12, date="2017-07-23", country="Germany", city="München" WHERE name="IV Münchener Sommerturnier 2017 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=3, date="2017-07-30", country="Germany", city="Köln" WHERE name="FIP 100 I Walls Padel Open" AND padel_serie="GPS-1200";
UPDATE tournaments_tournament SET club_id=4, date="2017-07-30", country="Germany", city="Karlsruhe" WHERE name="Karlsruher Lokales Turnier 2017" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=4, date="2017-08-06", country="Germany", city="Karlsruhe" WHERE name="Karlsruher Open 2017 - Herren" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=4, date="2017-08-06", country="Germany", city="Karlsruhe" WHERE name="Karlsruher Open 2017 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=17, date="2017-08-19", country="Germany", city="Weyhe" WHERE name="II Weyher Lokales Turnier 2017" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=25, date="2017-08-20", country="Germany", city="Hofheim am Taunus" WHERE name="Hofheimer Open 2017 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=25, date="2017-08-20", country="Germany", city="Hofheim am Taunus" WHERE name="Hofheimer Open 2017 - Herren" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=8, date="2017-09-03", country="Germany", city="Worms" WHERE name="Wormser Open 2017 - Herren" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=8, date="2017-09-03", country="Germany", city="Worms" WHERE name="Wormser Open 2017 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=11, date="2017-09-16", country="Germany", city="Schwaigern" WHERE name="Schwaigener Open 2017" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=17, date="2017-09-24", country="Germany", city="Weyhe" WHERE name="Weyher Open 2017" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=4, date="2017-09-30", country="Germany", city="Karlsruhe" WHERE name="Süd Deutsche Meisterschaft 2017 - Herren" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=4, date="2017-09-30", country="Germany", city="Karlsruhe" WHERE name="Süd Deutsche Meisterschaft 2017 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=14, date="2017-10-07", country="Germany", city="Berlin" WHERE name="Ost Deutsche Meisterschaft 2017" AND padel_serie="GPS-500";
--UPDATE tournaments_tournament SET club_id=3, date="2017-10-08", country="Germany", city="Köln" WHERE name="West Deutsche Meisterschaft 2017 - Herren" AND padel_serie="GPS-500";
--UPDATE tournaments_tournament SET club_id=3, date="2017-10-08", country="Germany", city="Köln" WHERE name="West Deutsche Meisterschaft 2017 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=2, date="2017-10-08", country="Germany", city="Hamburg" WHERE name="Nord Deutsche Meisterschaft 2017 - Herren" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=2, date="2017-10-08", country="Germany", city="Hamburg" WHERE name="Nord Deutsche Meisterschaft 2017 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=3, date="2017-10-22", country="Germany", city="Köln" WHERE name="Deutsche Meisterschaft 2017 - Herren" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=3, date="2017-10-22", country="Germany", city="Köln" WHERE name="Deutsche Meisterschaft 2017 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=3, date="2018-01-28", country="Germany", city="Köln" WHERE name="Kick-Off German Padel Series 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=3, date="2018-01-28", country="Germany", city="Köln" WHERE name="Kick-Off German Padel Series 2018" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=17, date="2018-02-17", country="Germany", city="Weyhe" WHERE name="Weyher Winter Turnier 2018" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=6, date="2018-02-25", country="Germany", city="Karlsruhe" WHERE name="Karlsruher Winter Turnier 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=3, date="2018-03-04", country="Germany", city="Köln" WHERE name="FIP 100 II Walls Padel Open" AND padel_serie="GPS-1200";
UPDATE tournaments_tournament SET club_id=4, date="2018-04-22", country="Germany", city="Karlsruhe" WHERE name="Karlsruher Open 2018" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=4, date="2018-04-22", country="Germany", city="Karlsruhe" WHERE name="Karlsruher Open 2018" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=16, date="2018-04-22", country="Germany", city="Cuxhaven" WHERE name="Cuxhavener Lokales Turnier" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=17, date="2018-05-20", country="Germany", city="Weyhe" WHERE name="Weyher Senioren Open 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=13, date="2018-05-27", country="Germany", city="Geretsried" WHERE name="Geretsrieder Open 2018" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=13, date="2018-05-27", country="Germany", city="Geretsried" WHERE name="Geretsrieder Open 2018" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=4, date="2018-05-31", country="Germany", city="Karlsruhe" WHERE name="Karlsruher Senioren Open 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=13, date="2018-06-10", country="Germany", city="Geretsried" WHERE name="Geretsrieder Lokales Turnier" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=2, date="2018-06-17", country="Germany", city="Hamburg" WHERE name="Hamburger Open 2018 Kat.A" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=2, date="2018-06-17", country="Germany", city="Hamburg" WHERE name="Hamburger Open 2018 Kat.B" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=5, date="2018-06-17", country="Germany", city="Karlsruhe" WHERE name="II Karlsruher Open 2018" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=3, date="2018-06-24", country="Germany", city="Köln" WHERE name="Kölner Senioren Open 2018" AND padel_serie="GPS-500" AND division="M45";
UPDATE tournaments_tournament SET club_id=3, date="2018-06-24", country="Germany", city="Köln" WHERE name="Kölner Senioren Open 2018" AND padel_serie="GPS-500"AND division="X40";
UPDATE tournaments_tournament SET club_id=1, date="2018-07-01", country="Germany", city="Berlin" WHERE name="Berliner Open 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=11, date="2018-07-07", country="Germany", city="Schwaigern" WHERE name="Schwaigerner Lokales Turnier" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=16, date="2018-07-14", country="Germany", city="Cuxhaven" WHERE name="Cuxhavener Open 2018" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=12, date="2018-07-29", country="Germany", city="München" WHERE name="Münchener Sommerturnier 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=12, date="2018-07-29", country="Germany", city="München" WHERE name="Münchener Sommerturnier 2018" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=8, date="2018-08-12", country="Germany", city="Worms" WHERE name="Wormser Lokales Turnier" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=18, date="2018-08-19", country="Germany", city="Espelkamp" WHERE name="Espelkamper Open 2018 Kat.A" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=18, date="2018-08-19", country="Germany", city="Espelkamp" WHERE name="Espelkamper Open 2018 Kat.B" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=17, date="2018-08-26", country="Germany", city="Weyhe" WHERE name="Weyher Open 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=17, date="2018-08-26", country="Germany", city="Weyhe" WHERE name="Weyher Open 2018" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=8, date="2018-09-02", country="Germany", city="Worms" WHERE name="Wormser Open 2018" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=13, date="2018-09-09", country="Germany", city="Geretsried" WHERE name="FIP-100 I Padel Open Geretsried" AND padel_serie="GPS-1200";
UPDATE tournaments_tournament SET club_id=11, date="2018-09-16", country="Germany", city="Schwaigern" WHERE name="Schweigerner Open 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=2, date="2018-09-16", country="Germany", city="Hamburg" WHERE name="Hamburger Meisterschaft Kat.A" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=2, date="2018-09-16", country="Germany", city="Hamburg" WHERE name="Hamburger Meisterschaft Kat.B" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=1, date="2018-09-23", country="Germany", city="Berlin" WHERE name="Berliner Senioren Open 2018" AND padel_serie="GPS-500" AND division="M45";
UPDATE tournaments_tournament SET club_id=1, date="2018-09-23", country="Germany", city="Berlin" WHERE name="Berliner Senioren Open 2018" AND padel_serie="GPS-500" AND division="X40";
UPDATE tournaments_tournament SET club_id=17, date="2018-09-29", country="Germany", city="Weyhe" WHERE name="II Weyher Lokales Turnier" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=4, date="2018-09-30", country="Germany", city="Karlsruhe" WHERE name="FIP-100 I International Padel Open Karlsruhe" AND padel_serie="GPS-1200";
UPDATE tournaments_tournament SET club_id=4, date="2018-10-07", country="Germany", city="Karlsruhe" WHERE name="Süd Deutsche Meisterschaft 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=3, date="2018-10-07", country="Germany", city="Köln" WHERE name="West Deutsche Meisterschaft 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=3, date="2018-10-07", country="Germany", city="Köln" WHERE name="West Deutsche Meisterschaft 2018" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=2, date="2018-10-07", country="Germany", city="Hamburg" WHERE name="Nord Deutsche Meisterschaft 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=1, date="2018-10-07", country="Germany", city="Berlin" WHERE name="Ost Deutsche Meisterschaft 2018" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=3, date="2018-12-09", country="Germany", city="Köln" WHERE name="FIP 100 III Walls Padel Open" AND padel_serie="GPS-1200";
UPDATE tournaments_tournament SET club_id=17, date="2019-03-02", country="Germany", city="Weyhe" WHERE name="Weyher Winter Turnier 2019" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=16, date="2019-04-20", country="Germany", city="Cuxhaven" WHERE name="Cuxhavener Lokales Turnier 2019" AND padel_serie="GPS-100" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=13, date="2019-05-05", country="Germany", city="Geretsried" WHERE name="1. DPS Seniorenturnier Geretsried - Damen" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=13, date="2019-05-05", country="Germany", city="Geretsried" WHERE name="1. DPS Seniorenturnier Geretsried - Herren" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=13, date="2019-05-05", country="Germany", city="Geretsried" WHERE name="1. DPS Seniorenturnier Geretsried - Mixed" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=3, date="2019-05-19", country="Germany", city="Köln" WHERE name="I Kölner Open 2019 - Mixed" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=3, date="2019-05-19", country="Germany", city="Köln" WHERE name="I Kölner Open 2019 - Damen" AND padel_serie="GPS-WOMEN";
UPDATE tournaments_tournament SET club_id=3, date="2019-05-19", country="Germany", city="Köln" WHERE name="I Kölner Open 2019 - Herren A" AND padel_serie="GPS-1000";
UPDATE tournaments_tournament SET club_id=3, date="2019-05-19", country="Germany", city="Köln" WHERE name="I Kölner Open 2019 - Herren B" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=3, date="2019-05-19", country="Germany", city="Köln" WHERE name="I Kölner Open 2019 - Herren Ü40" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=2, date="2019-06-02", country="Germany", city="Hamburg" WHERE name="1. DPS Seniorenturnier Hamburg - Damen" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=2, date="2019-06-02", country="Germany", city="Hamburg" WHERE name="1. DPS Seniorenturnier Hamburg - Herren" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=2, date="2019-06-02", country="Germany", city="Hamburg" WHERE name="1. DPS Seniorenturnier Hamburg - Mixed" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=2, date="2019-06-16", country="Germany", city="Hamburg" WHERE name="IV Hamburger Padel Meisterschaften Kat. A" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=2, date="2019-06-16", country="Germany", city="Hamburg" WHERE name="IV Hamburger Padel Meisterschaften Kat. B" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=17, date="2019-06-23", country="Germany", city="Weyhe" WHERE name="IV Weyher Open" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=3, date="2019-07-21", country="Germany", city="Köln" WHERE name="IV Walls Padel Open" AND padel_serie="GPS-1200";
UPDATE tournaments_tournament SET club_id=3, date="2019-07-21", country="Germany", city="Köln" WHERE name="IV Walls Padel Open" AND padel_serie="GPS-1200";
UPDATE tournaments_tournament SET club_id=11, date="2019-07-28", country="Germany", city="Schwaigern" WHERE name="Schwaigerner Open 2019" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=1, date="2019-08-04", country="Germany", city="Berlin" WHERE name="Berliner Open 2019 Kat. A" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=1, date="2019-08-04", country="Germany", city="Berlin" WHERE name="Berliner Open 2019 Kat. B" AND padel_serie="GPS-100";
UPDATE tournaments_tournament SET club_id=16, date="2019-08-04", country="Germany", city="Cuxhaven" WHERE name="Cuxhavener Open 2019" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=8, date="2019-08-10", country="Germany", city="Worms" WHERE name="Wormser Open 2019" AND padel_serie="GPS-250";
UPDATE tournaments_tournament SET club_id=2, date="2019-08-18", country="Germany", city="Hamburg" WHERE name="I Fip Promotion Padel Open Hamburg - Herren" AND padel_serie="GPS-1200" AND division="MO";
UPDATE tournaments_tournament SET club_id=2, date="2019-08-18", country="Germany", city="Hamburg" WHERE name="I Fip Promotion Padel Open Hamburg - Damen" AND padel_serie="GPS-WOMEN" AND division="WO";
UPDATE tournaments_tournament SET club_id=14, date="2019-09-01", country="Germany", city="Berlin" WHERE name="II Berliner Senioren Open 2019 - Damen" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=14, date="2019-09-01", country="Germany", city="Berlin" WHERE name="II Berliner Senioren Open 2019 - Herren" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=14, date="2019-09-01", country="Germany", city="Berlin" WHERE name="II Berliner Senioren Open 2019 - Mixed" AND padel_serie="GPS-500";
UPDATE tournaments_tournament SET club_id=13, date="2019-09-08", country="Germany", city="Geretsried" WHERE name="I FIP Promotion Padel Open Geretsried - Herren" AND padel_serie="GPS-1200" AND division="MO";
UPDATE tournaments_tournament SET club_id=13, date="2019-09-08", country="Germany", city="Geretsried" WHERE name="I FIP Promotion Padel Open Geretsried - Damen" AND padel_serie="GPS-WOMEN" AND division="WO";
COMMIT;
